# Generated by Django 6.0.3 on 2026-04-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('mini', 'Mini'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('auto', 'Auto'), ('bike', 'Bike')], default='mini', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=14)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='drivers/licenses/')),
                ('rc_photo', models.ImageField(blank=True, null=True, upload_to='drivers/rc/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=5.0)),
                ('total_rides', models.IntegerField(default=0)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='authsystem.user')),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
    ]
