# Generated by Django 6.0.3 on 2026-04-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_user_email_user_is_driver_user_name'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_online', 'is_approved'], name='drivers_is_onli_b94e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['vehicle_type'], name='drivers_vehicle_4e8406_idx'),
        ),
    ]
