# Generated by Django 6.0.3 on 2026-04-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('drop_lat', models.FloatField()),
                ('drop_lng', models.FloatField()),
                ('drop_address', models.CharField(blank=True, max_length=500)),
                ('vehicle_type', models.CharField(default='mini', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('searching_driver', 'Searching Driver'), ('driver_assigned', 'Driver Assigned'), ('driver_arriving', 'Driver Arriving'), ('ride_started', 'Ride Started'), ('ride_completed', 'Ride Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('estimated_fare', models.FloatField(blank=True, null=True)),
                ('final_fare', models.FloatField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='drivers.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='authsystem.user')),
            ],
            options={
                'db_table': 'rides',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_pickup', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to='drivers.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.ride')),
            ],
            options={
                'db_table': 'ride_requests',
            },
        ),
    ]
