# Generated by Django 6.0.3 on 2026-04-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_user_email_user_is_driver_user_name'),
        ('drivers', '0002_driver_drivers_is_onli_b94e9b_idx_and_more'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_status_376a74_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', 'status'], name='rides_passeng_fda548_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_driver__d736b9_idx'),
        ),
    ]
